FROM nginx:latest

COPY default.prod.conf /etc/nginx/conf.d/default.prod.conf

COPY customrlmaps.key /etc/ssl/customrlmaps.key
COPY customrlmaps.pem /etc/ssl/customrlmaps.pem
COPY cloudflare.crt /etc/ssl/cloudflare.crt